import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { StyledRoot } from './StyledRoot';
import CssBaseline from "@mui/joy/CssBaseline";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <StyledRoot>
            {children}
            <CssBaseline />
          </StyledRoot>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
